title: Jakub Podolak's Website
description: Personal website, blogposts and projects
theme: just-the-docs

url: https://jakubpodolak.space
# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
